---
title: "Yueqi Cao's Homepage"
---

Welcome to my homepage!

Currently I’m a master candidate in mathematics at Beijing Institute of Technology. My advisor is Prof. [Huafei Sun](https://math.bit.edu.cn/szdw/azcpl/js/shf/index.htm). My research focuses on the construction of the second fundamental form estimator on Euclidean submanifolds. A recent work can be found on [arXiv](https://arxiv.org/abs/1905.10725).

Here is a latest version of my [CV](cv.pdf).

### Education

- **2018--present** M.S. in Mathematics, Beijing Institute of Technology.
- **2014--2018** B.S. in Mathematics, Beijing Institute of Technology. [[Thesis (in Chinese)](/papers-and-ppts/本科毕业论文.pdf)]

### Research Interests

- Geometric and Statistical Inference
- Topological Data Analysis
- Signal Processing

### Preprints

- **Y.Cao**, D.Li, H.Sun, A.H.Assadi, S.Zhang, Efficient Weingarten Map and Curvature Estimation on Manifolds. [[URL](https://arxiv.org/abs/1905.10725)], [[PDF](/papers-and-ppts/weingarten-v2.pdf)]
- Y.Luo, S.Zhang, **Y.Cao**, H.Sun, Geometric Characteristics of Wasserstein Metric on SPD(n). [[URL](https://arxiv.org/abs/2012.07106)], [[PDF](/papers-and-ppts/luo-v1.pdf)]

### Publications  

- F.Sun, **Y.Cao**, S.Zhang, H.Sun, The Bayesian Inference of Pareto Models Based on Information Geometry. *Entropy*, 2021. [[URL](https://www.mdpi.com/1099-4300/23/1/45)], [[PDF](/papers-and-ppts/entropy-sun.pdf)] 
- J.Yi, S.Zhang, **Y.Cao**, E.Zhang, H.Sun, Rigid Shape Registration Based on Extended Hamiltonian Learning. *Entropy*, 2020. [[URL](https://www.mdpi.com/1099-4300/22/5/539)], [[PDF](/papers-and-ppts/entropy-yi.pdf)]
- Y.Wang, H.Sun, **Y.Cao**, S.Zhang, Torsion Discriminance for Stability of Linear Time-Invariant Systems. *Mathematics*, 2020. [[URL](https://www.mdpi.com/2227-7390/8/3/386)], [[PDF](/papers-and-ppts/mathematics-wang.pdf)] 

### Conference Papers

- **Y.Cao**, S.Zhang, F.Yan, W.Li, F.Sun, H.Sun, Unsupervised Environmental Sound Classification Based On Topological Persistence. *2019 IEEE International Conference on Signal, Information and Data Processing (ICSIDP)*, Chongqing, China, 2019. [[URL](https://ieeexplore.ieee.org/document/9173135)], [[PDF](/papers-and-ppts/icsidp2019cao.pdf)]
- S.Zhang, **Y.Cao**, W.Li, F.Yan, Y.Luo, H.Sun, A New Riemannian Structure in SPD(n). *2019 IEEE International Conference on Signal, Information and Data Processing (ICSIDP)*, Chongqing, China, 2019. [[URL](https://ieeexplore.ieee.org/document/9173017)], [[PDF](/papers-and-ppts/icsidp2019zhang.pdf)]
- A.Xiong, A.Assadi, **Y.Cao**, Calculating Persistence Homology of Attractors in High-Dimensional Chaotic Systems, *2017 International Conference on Computational Science and Computational Intelligence (CSCI)*, Las Vegas, NV, 2017. [[URL](https://ieeexplore.ieee.org/document/8560778)], [[PDF](/papers-and-ppts/anda2017.pdf)]

### Talks

- **Y.Cao**, Data Science from a Topological Viewpoint. *The Second International Conference on Mathematical Characterization, Analysis and Applications of Complex Information (CMCAA 2018)*, Beijing, China, 2018. [[URL](https://math.bit.edu.cn/cmcaa2018/program2018/index.htm)], [[PPT](/papers-and-ppts/cmcaa2018.pptx)] 

### Awards

- 2017 Winning Prize of Geometry and Topology in 8th S.T.Yau College Student Mathematics Contests. 
- 2017 Winning Prize of Team in 8th S.T.Yau College Student Mathematics Contests. 
- 2016 Grand Prize in 1st Excellence 9 College Student Mathematics Contests. 
- 2016 Second Prize in CUMCM-2016 (Contemporary Undergraduate Mathematical Contest in Modeling). 

### Scholarships

- 2020 Second Prize of CASC Scholarship. 
- 2019 National Scholarship for Graduate Students. 
- 2017 Second Prize of Innovation Scholarship of Industry and Information Technology of People's Republic of China. 
- 2016&2015 Dwen Scholarship. 
- 2014--2018 Undergraduate Student Scholarship. 

### Other Links
[[arXiv](https://arxiv.org/)], [[ORCID](https://orcid.org/0000-0001-8856-2902)], [[ResearchGate](https://www.researchgate.net/profile/Yueqi_Cao2)], [[Github](www.github.com/yueqicao)], [[中文版](index-ch.md)]



